---
galaxy_info:
  author: Prakhar Srivastava
  description: Validation role for Private LLMaaS workshop on AWS
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - validation
    - openshift
    - llmaas
    - workshop

dependencies: []
